### PR TITLE
Use https as default protocol (#15)

### PR DESCRIPTION
**Pull request by jaksah**

### CODE REVIEW

**Comment by jaksah** [comment]
Related to #15

**Comment by gajus** [comment]
Is this different from https://github.com/gajus/youtube-player/pull/27 ?

**Comment by jaksah** [comment]
ah, @resistdesign was quicker. They are the same. Closing this PR as per above comment

**Comment by resistdesign** [comment]
@jaksah Yeah, sorry, I realized I had it backwards just as @gajus was merging the first one :P

**Pull request closed without merging**
