### PR TITLE
Remove lodash to reduce library size

### PR DESCRIPTION
**Pull request by phamminh91**
Lodash is a huge library. Since we only need `_.forEach` and `_.isString`, I have replaced it with plain javascript functions.

### CODE REVIEW

**Comment by gajus** [comment]
https://github.com/gajus/youtube-player/issues/29

**Comment by resistdesign** [comment]
@gajus It would seem to me that using plain javascript is a better move in this case given that only the 2 function are used. Using library specific babel plugins seems like a potential maintenance issue. That's just my perspective.

**Comment by gajus** [comment]
I simply don't see benefit of not using lodash. You are re-implementing the same utilities that lodash provides.

However, I am not actively engaged with this code base development. Therefore, you have more right to judge whats right. Please proceed merging this at your discretion.

**Comment by phamminh91** [comment]
I think there are 2 main benefits to this approach:
- smaller file size (we don't need lodash for these simple functions)
- any project that use `youtube-player` does not have to change the build process to exclude redundant part of lodash. (hence can benefits from small file size)

I'd like to hear your thoughts on this. Thanks!

**Comment by gajus** [comment]
> I think there are 2 main benefits to this approach:

There is absolutely no reasonable way to avoid all dependencies that use lodash. It is such a ubiquitous dependency that chances are that if not a direct dependency of the project, then a sub-dependency of the project will be using it.

The problem is not using lodash. The problem usually is how it is being used.

Regardless, I have no objections to this being merged.

**Comment by resistdesign** [comment]
@gajus What do you think about just importing the 2 functions we need and not all of lodash?

**Comment by gajus** [comment]
> @gajus What do you think about just importing the 2 functions we need and not all of lodash?

Thats what `babel-plugin-lodash` already does.

**Comment by resistdesign** [comment]
@gajus But it requires you to add a transform to your build system config right?

**Comment by gajus** [comment]
> @gajus But it requires you to add a transform to your build system config right?

No, this plugin is on our end.

https://github.com/gajus/youtube-player/blob/d000e1b785fbc5e9f19bdb60117273bc95511adf/.babelrc#L3

Pull the repository and run `npm install && npm run build`. Now see `./dist`. You will find that lodash import statements have been replaced.

**Comment by resistdesign** [comment]
@gajus What about here where you mention something about a webpack plugin? https://github.com/gajus/youtube-player/issues/29

**Comment by gajus** [comment]
> @gajus What about here where you mention something about a webpack plugin? #29

It will further reduce the bundle size. It will not be necessary as of lodash v5, though.

**Comment by resistdesign** [comment]
@phamminh91 I'm going to close this because I think being able to just use lodash and not worry about how you're importing it can be a benefit to maintenance. I personally don't like massive util libs like lodash for my own reasons but I recognize them as something that the community enjoys using so I think lodash stays, at least for now :)

**Pull request closed without merging**
