### PR TITLE
Fix YouTubePlayer.promisifyPlayer

### LINKED ISSUE #36: YouTubePlayer.promisifyPlayer is making proxy functions with incorrect `this`
https://github.com/gajus/youtube-player/blob/5e68d9a586f5bdd960098a674a489c9e06685e62/src/YouTubePlayer.js#L47

`player[functionName]` should be applied with `player` as `this` value, instead of `null`.

### PR DESCRIPTION
**Pull request by youpy**
fix #36

### CODE REVIEW

**Comment by resistdesign** [comment]
@gajus Is this released on it's own somehow or do you need to release it?

**Comment by gajus** [comment]
> @gajus Is this released on it's own somehow or do you need to release it?

Releases on its own.

Don't forget to add "BREAKING CHANGE" commit message if you are making a breaking change. See https://github.com/semantic-release/semantic-release#major-breaking-release

**Comment by resistdesign** [comment]
@gajus Ok, thank you for that link. This is just a patch though right? And, how does it handle that?

**Comment by gajus** [comment]
Well, you have already merged it, so it is too late to specify that it is a patch.

When merging, you need to choose option "squash & commit". Then you need to write a commit message following the established convention, https://github.com/semantic-release/semantic-release#default-commit-message-format.

**Comment by youpy** [comment]
Since version 4.1.0 does not work properly, it needs to be released with the current revision.

**Comment by resistdesign** [comment]
@gajus What needs to be done at this point?

**Comment by gajus** [comment]
> @gajus What needs to be done at this point?

To achieve what?

**Comment by resistdesign** [comment]
To fix any issues with the current release or get it released if it's not.

**Comment by gajus** [comment]
> @gajus To fix any issues with the current release or get it released if it's not.

Well... one way is:

```bash
git commit -m 'fix: force patch release' --allow-empty
```

**Comment by resistdesign** [comment]
Right to `master` or a some temp branch?

**Comment by gajus** [comment]
> Right to master or a some temp branch?

Master is protected, therefore unfortunately you need to raise a PR and then merge it.

**Comment by resistdesign** [comment]
Ok

**Comment by samelwitt** [comment]
Did this happen? Still broken for me.

**Comment by gajus** [comment]
> Did this happen? Still broken for me.

What are the symptoms?

**Comment by samelwitt** [comment]
@gajus The issue I described in https://github.com/gajus/react-youtube-player/issues/11

When I debug, I see that react-youtube-player is properly firing playVideo(), but youtube-player never fires the event to youtube api.

**Comment by gajus** [comment]
Whats the relation to this package, this pull request?

**Comment by youpy** [comment]
@samelwitt what version of `youtube-player` did you use when you ran the demo?

**Comment by samelwitt** [comment]
> what version of youtube-player did you use when you ran the demo?

@youpy 2.0.0

> Whats the relation to this package, this pull request?

Sorry for the confusion -- I demo'd react-youtube-player, which has youtube-player 2.0.0 as a dependency. I was debugging to see if the promisifyPlayer was the source of the issue, and came across this thread. So I wanted to see if the PR from resistdesign happened and possibly fixed the issue I'm having.

**Comment by resistdesign** [comment]
@samelwitt `react-youtube-player` would need to use the new version of `youtube-player`.

**Pull request merged**
