### PR TITLE
Add getSphericalProperties function for 360 videos

### PR DESCRIPTION
**Pull request by zymotik**
This function returns an object. When a 360 video is loaded, the object has values like so:

```json
{
  "fov": 100.00004285756798
  "pitch": 0
  "roll": 0
  "yaw": 0
}
```

See: https://developers.google.com/youtube/iframe_api_reference#Spherical_Video_Controls

### CODE REVIEW

**Review by resistdesign — APPROVED** [review]

**Review by resistdesign — CHANGES_REQUESTED** [review]
You should probably make an entry in types.js for getSphericalProperties

**Comment by resistdesign** [comment]
@gajus the build failure seems unrelated to the commit but I'm not sure.

**Review by resistdesign — APPROVED** [review]
Awesome!

**Comment by zymotik** [comment]
@resistdesign I have raised another PR that addresses the issues with the Jenkins build. See https://github.com/gajus/youtube-player/pull/87

If that gets approved, I'll merge into this PR. 👍

**Comment by resistdesign** [comment]
@zymotik ok, build fix is merged! Now you just need to update this branch and resolve the conflicts and then it should be good!!!

**Comment by resistdesign** [comment]
@gajus @zymotik NOTE: I reformatted the title of the merge when I merged in the changes, I'm hoping I did it the right way to trigger a semantic release.

**Comment by zymotik** [comment]
@gajus Please can you help us with a release of this new version? I am not sure on how to do this.

**Pull request merged**
